name: Python Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
      - lab3
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run:
          python -m unittest devops/lab3/tests/test_app.py
  publish:
    needs: run_tests
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Vault Action - Fetch Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_SERVER }}
          method: userpass
          username: ${{ secrets.VAULT_LOGIN }}
          password: ${{ secrets.VAULT_PWD }}
          secrets: |
            kv/lab3-secret DOCKER_LOGIN | DOCKER_LOGIN ;
            kv/lab3-secret DOCKER_NAME | DOCKER_NAME ;
            kv/lab3-secret DOCKER_PWD | DOCKER_PWD ;
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

      - name: Login
        run: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      - name: Debug GitHub ref
        run: echo ${GITHUB_REF}

      - uses: actions/checkout@main
      - name: Build
        run: docker build -t $DOCKER_LOGIN/$DOCKER_NAME:${GITHUB_REF:11} -f devops/lab3/web/Dockerfile .

      - name: Push
        run: docker push $DOCKER_LOGIN/$DOCKER_NAME:${GITHUB_REF:11}
  deploy:
    needs: [ publish ]
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Vault Action - Fetch Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_SERVER }}
          method: userpass
          username: ${{ secrets.VAULT_LOGIN }}
          password: ${{ secrets.VAULT_PWD }}
          secrets: |
            kv/lab3-secret DOCKER_LOGIN | DOCKER_LOGIN ;
            kv/lab3-secret DOCKER_NAME | DOCKER_NAME ;
            kv/lab3-secret DEPLOYMENT_SERVER | DEPLOYMENT_SERVER ;
            kv/lab3-secret DEPLOYMENT_TOKEN | DEPLOYMENT_TOKEN ;
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}


      - name: Set Tag
        run: echo "TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV

      - name: Send webhook for deploy
        run: |
          curl --silent --show-error --fail -X POST "$DEPLOYMENT_SERVER" \
            -H "Authorization: $DEPLOYMENT_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "owner": "'"$DOCKER_LOGIN"'",
              "repository": "'"$DOCKER_NAME"'",
              "tag": "'"${{ env.TAG }}"'",
              "ports": {"5000": 5000}
            }'
