name: Python Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
      - lab3
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd devops/lab3
          python -m unittest tests/test_app.py